# Generated by Django 4.2.30 on 2026-05-15 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compensation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('SALARY_INCREASE', 'Salary Increase'), ('PROMOTION', 'Promotion'), ('MARKET_ADJUSTMENT', 'Market Adjustment')], max_length=50)),
                ('current_salary_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_of_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_salary_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_proposals', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_salary_changes', to=settings.AUTH_USER_MODEL)),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='compensation.reviewcycle')),
            ],
        ),
    ]
